import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Instalasi',
      items: [
        'instalasi/library',
        'instalasi/starter-kit',
        'instalasi/quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Komponen',
      items: [
        'komponen/button',
        'komponen/modal',
        'komponen/input',
        'komponen/dropdown',
        'komponen/menu',
        'komponen/table',
        'komponen/card',
        'komponen/badge',
        'komponen/callout',
        'komponen/checkbox',
        'komponen/radio',
        'komponen/switch',
        'komponen/select',
        'komponen/textarea',
        'komponen/tabs',
        'komponen/toast',
        'komponen/tooltip',
        'komponen/accordion',
        'komponen/avatar',
        'komponen/breadcrumbs',
        'komponen/navbar',
        'komponen/navlist',
        'komponen/pagination',
        'komponen/skeleton',
        'komponen/progress',
        'komponen/separator',
        'komponen/heading',
        'komponen/field',
        'komponen/otp-input',
        'komponen/slider',
        'komponen/file-upload',
        'komponen/color-picker',
        'komponen/pillbox',
        'komponen/popover',
        'komponen/timeline',
        'komponen/icons',
        'komponen/layout',
        'komponen/link',
        'komponen/command',
        'komponen/context',
        'komponen/calendar',
        'komponen/combobox',
        'komponen/date-picker',
        'komponen/time-picker',
        'komponen/empty',
        'komponen/image-diff',
        'komponen/kbd',
        'komponen/key-value',
        'komponen/repeater',
        'komponen/rover',
        'komponen/tags-input',
        'komponen/theme-switcher',
        'komponen/wizard',
        'komponen/alert-utilities',
        'komponen/editor-composer',
        'komponen/kanban',
        'komponen/chart-carousel',
      ],
    },
    {
      type: 'category',
      label: 'Starter Kit',
      items: [
        'starter-kit/overview',
        'starter-kit/features',
        'starter-kit/authentication',
        'starter-kit/settings',
      ],
    },
    'kustomisasi',
    'kontribusi',
  ],
};

export default sidebars;
